theme = "everforest_dark"

[editor]
true-color = true
line-number = "absolute"
mouse = true
middle-click-paste = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
